# Generated by Django 5.1.4 on 2025-02-06 02:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logp', '0004_rename_password1_registerationform_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerationform',
            name='id',
        ),
        migrations.AddField(
            model_name='registerationform',
            name='user_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
