# Generated by Django 5.1.4 on 2025-02-06 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logp', '0005_remove_registerationform_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegisterationForm',
            new_name='RegistrationForm',
        ),
    ]
