# Generated by Django 5.1.4 on 2025-02-06 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logp', '0006_rename_registerationform_registrationform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationform',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
