# Generated by Django 5.1.4 on 2025-02-06 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logp', '0007_alter_registrationform_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationform',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
