# Generated by Django 5.1.4 on 2025-03-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logp', '0008_alter_registrationform_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationform',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='registrationform',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrationform',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
