# Generated by Django 5.1.4 on 2025-03-26 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logp', '0010_rename_is_admin_registrationform_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationform',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='registrationform',
            name='user_permissions',
        ),
    ]
