# Generated by Django 5.1.4 on 2025-03-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logp', '0012_registrationform_groups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationform',
            old_name='is_staff',
            new_name='is_admin',
        ),
        migrations.RemoveField(
            model_name='registrationform',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='registrationform',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='registrationform',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='mname',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
