# Generated by Django 5.1.4 on 2025-03-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logp', '0013_rename_is_staff_registrationform_is_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationform',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
