# Generated by Django 5.1.4 on 2025-03-26 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logp', '0015_registrationform_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationform',
            name='is_staff',
        ),
    ]
