# Generated by Django 5.1.4 on 2025-04-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logp', '0016_remove_registrationform_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationform',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
