# Generated by Django 5.1.4 on 2025-01-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_id', models.CharField(max_length=6)),
                ('acc_name', models.CharField(max_length=100)),
                ('acc_desc', models.TextField(max_length=300)),
                ('acc_prize', models.CharField(max_length=100)),
            ],
        ),
    ]
