# Generated by Django 5.1.4 on 2025-01-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories',
            name='image',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
