# Generated by Django 5.1.4 on 2025-01-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_accessories_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='acc_desc',
            field=models.TextField(max_length=1000),
        ),
    ]
