# Generated by Django 5.1.4 on 2025-01-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_accessories_acc_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories',
            name='acc_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
