# Generated by Django 5.1.4 on 2025-02-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_spare'),
    ]

    operations = [
        migrations.AddField(
            model_name='spare',
            name='typ',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
