# Generated by Django 5.1.4 on 2025-02-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_spare_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='spare',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
