# Generated by Django 5.1.4 on 2025-03-12 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_order_payment_id'),
        ('logp', '0008_alter_registrationform_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logp.registrationform'),
        ),
    ]
