# Generated by Django 5.1.4 on 2025-04-16 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='spare',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
