# Generated by Django 5.1.4 on 2025-05-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0021_productrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spare',
            name='stock',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
